const deckMeta={title:'Errors and power',course:4,version:4,date:'22 September 2026',minutes:47.5,pdf:'M2_topic10_errors-and-power_26-27.pdf',description:'Medical decisions and their errors, animated sampling distributions, the logic of sample-size planning, then multiple testing, p-hacking, planned correction, HARKing and replicability.'};







const slides=[
{title:'Errors and power',steps:1,printSteps:[0],minutes:.5,className:'title-slide',render:()=>`<p class="course">DAS · Statistics</p><h1>Errors and power</h1><p class="title-question">What can a study detect, miss or falsely declare?</p><div class="route"><span>Type I and II errors</span><span>Power and study size</span><span>Multiple testing, p-hacking and HARKing</span></div>`},
{title:'Does the drug have an effect?',steps:4,printSteps:[1,3],minutes:3,className:'narrative',render:k=>`<p class="lead">H₀: no effect on the outcome. H₁: an effect on the outcome.</p>${medicalTable(k)}<p class="bottomline">${k>=3?'Our sample gives a decision. The population determines whether it is correct.':'In JAMA, the outcome was disappearance of sore-throat symptoms at a specified time.'}</p>`},
{title:'Type I error: falsely declaring an effect',steps:3,printSteps:[2],minutes:2.5,className:'narrative curve-slide',render:k=>`<p class="lead">Return to the simple example: H₀ says the prevalence is 20%.</p>${proportionFigure({markers:k>=1?[30]:[],regions:true})}<p class="readout">${k===0?'If the true prevalence is 20%, observations in either tail produce a false rejection.':k===1?'A sample with 30% prevalence would reject H₀, even though H₀ is true here.':`${math(tex`\alpha=\Pr(\text{reject }H_0\mid H_0\text{ true})\approx5\%`)}`}</p><p class="bottomline small">The 5% calibration is approximate for this proportion test.</p>`},
{title:'A real difference needs a specified value',steps:3,printSteps:[0,2],minutes:3,className:'narrative power-slide',render:(k,print)=>`<p class="lead">The test still asks whether prevalence is 20%.</p>${powerHost({n:100,p1:k===1?.25:.3,stage:k===0?0:1},print,'none')}<p class="readout">${['What would samples look like if H₀ were false?','Suppose the true prevalence is 25%. The estimates now centre on 25%.','Suppose it is 30%. The decision boundaries still come from H₀.'][k]}</p><p class="bottomline small">We specify an alternative value to calculate the chance of missing it.</p>`},
{title:'Type II error and statistical power',steps:3,printSteps:[0,2],minutes:4,className:'narrative power-slide',render:(k,print)=>`<p class="lead">Suppose the true prevalence is 30%, while H₀ says 20%.</p>${powerHost({n:100,p1:.3,stage:k===0?2:3},print,'none')}<p class="readout">${k===0?'Red area: the test does not reject, although H₀ is false.':k===1?'Green area: the test detects the real difference.':math(tex`\text{Power}=1-\beta`)}</p><p class="bottomline small">${k===0?'β is the probability of missing this specified difference.':'Both rejection tails contribute to the green area under the alternative.'}</p>`},
{title:'More people make estimates more precise',steps:3,printSteps:[0,1,2],minutes:4,className:'narrative power-slide',render:(k,print)=>`<p class="lead">The true prevalence stays at 30%. The significance level stays at 5%.</p>${powerHost({n:[100,200,400][k],p1:.3,stage:3},print)}<p class="bottomline">The curves narrow, the critical limits move towards 20%, and power increases.</p>`},
{title:'Power depends on the effect and the threshold',steps:3,printSteps:[0,1,2],minutes:3,className:'narrative power-slide',render:(k,print)=>`<p class="lead">Keep 100 people. ${k===0?'Consider a smaller real difference.':k===1?'Now consider a larger real difference.':'Now require stronger evidence before rejecting.'}</p>${powerHost({n:100,p1:k===0?.25:.3,alpha:k===2?.01:.05,stage:3},print,'none')}<p class="readout">${['25% rather than 20% is harder to detect.','30% rather than 20% is easier to detect.','A stricter significance level reduces the chance of detection.'][k]}</p><p class="bottomline small">A power statement needs a specified effect, sample size and significance level.</p>`},
{title:'Why plan the sample size?',steps:4,printSteps:[1,3],minutes:3.5,className:'narrative ethical',render:k=>`<p class="lead">A real effect can exist and still be missed by an underpowered study.</p><div class="stack"><p><strong>Funders and research teams</strong><br>Commit money and time to answer a useful question.</p>${reveal(k>=1,'<p><strong>Participants</strong><br>Contribute their time and accept burdens or risks.</p>')}${reveal(k>=2,'<p><strong>Future patients</strong><br>May wait longer for a useful treatment if its benefit is missed.</p>')}</div>${reveal(k>=3,'<p class="bottomline teal">Are we giving this study a reasonable chance to answer its question?</p>')}`},
{title:'The logic of sample-size planning',steps:3,printSteps:[0,2],minutes:4,className:'narrative power-slide',render:(k,print)=>{const target=k===2?.9:.8,n=k===0?100:plannedN(target);return `<p class="lead">If the true prevalence is 30%, what size gives ${pct(target)} power?</p>${powerHost({n,p1:.3,stage:3},print,'none')}<p class="readout">${k===0?'At 100 people, the detection probability is below the target.':`About ${n} people reach ${pct(target)} power in this Normal approximation.`}</p><p class="bottomline small">${math(tex`\alpha=0.05`)}. A target power of ${pct(target)} means ${math(tex`\beta=${(1-target).toFixed(2)}`)} for this assumed effect.</p>`;}},
{title:'What the JAMA study planned',steps:3,printSteps:[2],minutes:2,className:'narrative jama-plan',render:k=>`<p class="lead">Two treatment groups. Primary outcome: symptom resolution at 24 hours.</p><div class="two-stats"><div><p class="medium">Placebo assumption</p><p class="big">11%</p></div><div><p class="medium">Dexamethasone assumption</p><p class="big teal">29%</p></div></div><p class="small center muted">Under the null hypothesis, the two groups have the same resolution rate.</p>${reveal(k>=1,`<p class="callout">Planned alternative: ${math(tex`29\%-11\%=18\%`)} absolute difference.<br>Significance level: ${math(tex`5\%`)}. Target power: ${math(tex`90\%`)}.</p>`)}${reveal(k>=2,'<p class="bottomline">The article used two-sided p-values: a difference in either direction.</p>')}`},
{title:'Jelly beans and acne',steps:4,printSteps:[0,1,2,3],minutes:3,className:'narrative comic',render:k=>`<p class="lead">${['One planned question: are jelly beans linked to acne?','Now test the colours one by one.','Twenty colours create twenty opportunities to find a result.','The headline reports only the green result.'][k]}</p><img class="image-large" src="assets/${['jelly-question.png','jelly-tests-a.png','jelly-tests-b.png','jelly-headline.png'][k]}" alt="${['xkcd initial jelly-bean question','First ten colour tests','Next ten colour tests including green','Headline selecting the green jelly-bean result'][k]}"><p class="comic-source">xkcd: Significant, Randall Munroe · xkcd.com/882</p><p class="bottomline">${k===0?'What happens to a 5% risk when one question becomes many?':'The reader needs to know how many questions the researchers examined.'}</p>`},
{title:'A 5% risk for each test',steps:3,printSteps:[2],minutes:2.5,className:'narrative',render:k=>`<p class="lead">Imagine 20 independent tests, with all 20 null hypotheses true.</p><div class="stack"><p class="medium">Each test has a 5% chance of a false rejection.</p>${reveal(k>=1,formula(tex`\Pr(\text{no false rejection})=0.95^{20}\approx0.36`))}${reveal(k>=2,formula(tex`\Pr(\text{at least one false rejection})=1-0.95^{20}\approx0.64`))}</div><p class="bottomline">About 64% of such sets contain at least one false rejection.</p>`},
{title:'P-hacking',steps:3,printSteps:[0,1,2],minutes:2.5,className:'narrative p-hacking-slide',render:k=>`<p class="p-hacking-definition"><span class="term">P-hacking</span> refers to using flexible analyses or repeated testing to search for a statistically significant result, then <span class="term">reporting only the result that worked.</span></p>${reveal(k>=1,testsGrid(k>=2?'selected':'all'))}${reveal(k>=1,'<p class="fine p-hacking-note">Illustrative significance values, not data from the cartoon.</p>')}<p class="bottomline">${['The reported result does not show the full search.','Twenty colours create twenty opportunities to obtain a significant result.','Reporting only green hides the other nineteen tests.'][k]}</p>`},
{title:'Bonferroni for a planned family of tests',steps:3,printSteps:[2],minutes:2.5,className:'narrative',render:k=>`<p class="lead">Aim for at most a 5% chance of any false rejection across the family.</p>${formula(tex`\text{significance level for each test}=\frac{\alpha}{m}`)}${reveal(k>=1,formula(tex`m=20,\quad\alpha=0.05:\qquad\frac{0.05}{20}=0.0025`))}${reveal(k>=2,'<p class="callout">A p-value of 0.02 would no longer pass this threshold.</p>')}<p class="bottomline">Bonferroni addresses a defined set of tests, not a hidden adaptive search.</p>`},
{title:'HARKing',steps:3,printSteps:[0,2],minutes:1.5,className:'narrative harking-slide',render:k=>`<div class="harking-grid"><div class="harking-copy"><p class="lead"><span class="term">HARKing</span> means Hypothesizing After the Results are Known.</p>${reveal(k>=1,'<p class="medium">A <span class="term">post hoc</span> hypothesis is presented as if it were an <span class="term">a priori</span> hypothesis.</p>')}${reveal(k>=2,'<ol class="hark-example"><li>Test the jelly-bean colours.</li><li>Green happens to be significant.</li><li>Present green as the original hypothesis.</li></ol>')}</div><figure class="harking-figure"><img class="harking-image" src="assets/jelly-headline.png" alt="Newspaper headline claiming that green jelly beans are linked to acne"><figcaption class="harking-source">Source: xkcd, “Significant,” Randall Munroe · xkcd.com/882</figcaption></figure></div><p class="bottomline">New hypotheses are useful. Their exploratory origin should be clear.</p>`},
{title:'Replicability of published psychology findings',steps:3,printSteps:[0,2],minutes:2.5,className:'narrative replication-slide',render:k=>`<p class="lead">The Open Science Collaboration repeated 100 published psychology studies.</p><img class="replication-figure" src="assets/osc-2015-figure-1-000.jpg" alt="Density plots comparing original and replication study significance values and effect sizes"><p class="replication-note">Original effect directions were coded positive. Negative replication values indicate effects in the opposite direction.</p><div class="replication-findings">${reveal(k>=1,'<p><strong>Significant results</strong><br>97% in the original studies; 36% in the replications.</p>')}${reveal(k>=2,'<p><strong>Mean effect size</strong><br>0.40 originally; 0.20 in replications, with some effects reversed.</p>')}</div><p class="replication-source">Open Science Collaboration, <em>Science</em>, 2015. Figure 1. doi:10.1126/science.aac4716</p>`},
{title:'Planning and reporting',steps:3,printSteps:[2],minutes:3.5,className:'narrative',render:k=>`<div class="stack"><p class="medium"><strong>Before collecting data</strong><br>Specify the primary outcome, hypotheses and significance level.<br>Choose a meaningful effect and a sample size that can detect it.</p>${reveal(k>=1,'<p class="medium"><strong>When interpreting results</strong><br>Read the effect estimate and its confidence interval.<br>Which clinically important effects does the confidence interval rule out, and which does it still allow?</p>')}${reveal(k>=2,'<p class="medium"><strong>When reporting</strong><br>Show the primary result and the relevant secondary results.<br>Account for multiple testing.</p>')}</div><p class="bottomline teal">The aim is useful evidence for the question that justified the study.</p>`},
{title:'Thank you',steps:1,printSteps:[0],minutes:0,className:'thank-you-slide',render:()=>'<p class="thank-you-message">Thank you very much for your attention</p>'}
];
