 


slides[2].minutes=1.5;
const coverageBuilds=[{n:100,level:95,total:1,phase:2},{n:100,level:95,total:3,phase:2},{n:100,level:95,total:4,phase:2},{n:100,level:95,total:4,phase:1},{n:100,level:95,total:1000,phase:0},{n:100,level:95,total:1000,phase:1},{n:100,level:95,total:1000,phase:2},{n:25,level:95,total:1000,phase:2},{n:400,level:95,total:1000,phase:2},{n:1600,level:95,total:1000,phase:2},{n:1600,level:99,total:1000,phase:2}];
slides.push(
 {title:'Disease prevalence',minutes:1,steps:2,render:k=>`<p class="lead">What proportion of adults in a defined region<br>have the disease on a given date?</p><div class="rule"></div><div class="cols" style="margin-top:38px"><div><p class="medium">Suppose that the true prevalence is</p><div class="formula">${math(tex`p=20\%`,true)}</div><p class="medium muted">We know p here to study the sampling process.</p></div><div><p class="medium">Disease status: present or absent</p><div class="${showIf(k)}"><p class="medium">We assume</p><p class="medium teal">Random, independent sampling<br>Accurate measurement</p></div></div></div><p class="bottomline">Later, we will return to the situation where p is unknown.</p>`},
 {title:'An observed sample',minutes:1.5,steps:4,printSteps:[1,3],sampling:true,render:k=>`${samplingPicture(0,k)}<p class="bottomline ${showIf(k>=3)}">${math(tex`\widehat p=18/100=18\%`)} &nbsp; An estimate of the population prevalence.</p>`},
 {title:'The estimator and an estimate',minutes:1.5,steps:3,render:k=>`<p class="lead">The estimator is the rule we apply to every sample.</p><div class="cols" style="margin-top:35px"><div><p class="medium">Code disease status</p><div class="formula">${math(tex`X_i=\begin{cases}1&\text{present}\\0&\text{absent}\end{cases}`,true)}</div></div><div class="${showIf(k>=1)}"><p class="medium teal">Estimator: the sample proportion</p><div class="formula">${math(tex`\widehat p=\frac{X_1+\cdots+X_n}{n}`,true)}</div><p class="small center">An average of 0/1 observations</p></div></div><div class="rule"></div><div class="${showIf(k>=2)}"><p class="medium">On the previous sample, the rule gave</p><div class="formula">${math(tex`\widehat p=\frac{18}{100}=18\%`,true)}</div><p class="medium center teal">18% is the observed estimate.</p></div>`},
 {title:'Repeated samples from the same population',minutes:2,steps:5,printSteps:[0,2,4],sampling:true,render:k=>{const i=k===0?0:k<=2?1:2,phase=k===1||k===3?1:3,h=k===0?1:k===1?1:k<=3?2:3;return `${samplingPicture(i,phase,h)}<p class="bottomline">${k===4?'How far might an estimate fall from the true prevalence of 20%?':'Same population. Same sample size. The estimate can change.'}</p>`;}},
 {title:'The distribution of sample proportions',minutes:3,steps:3,printSteps:[1,2],className:'simulation',simulation:true,render:k=>histogramScene(k?1000:0,k>=2)},
 {title:'The central limit theorem',minutes:2,steps:3,className:'clt-slide',render:k=>`<p class="medium">${math(tex`\widehat p`)} is the average of the independent 0/1 observations.</p><div class="clt-layout"><div>${approximationPlot(100,1000,{labels:k>=2,compact:true})}</div><div><p class="medium">For a large sample</p><div class="formula ${showIf(k>=1)}">${math(tex`\widehat p\ \overset{\text{approx.}}{\sim}\ \mathcal N\!\left(p,\,\frac{p(1-p)}{n}\right)`,true)}</div><div class="${showIf(k>=2)}"><p class="medium rose">Centre: mean p</p><p class="medium">Spread: variance ${math(tex`\frac{p(1-p)}{n}`)}</p><p class="small muted">The standard error is its square root.</p></div></div></div><p class="bottomline">Enough expected cases and non-cases are needed for a useful approximation.</p>`},
 {title:'Where the 4 percentage points come from',minutes:2,steps:3,printSteps:[1,2],render:k=>`<p class="lead">The standard error is the standard deviation of the estimates.</p><p class="medium muted">It describes the spread across repeated samples.</p><div class="formula" style="margin:32px 0">${math(tex`\mathrm{SE}(\widehat p)=\sqrt{\frac{p(1-p)}{n}}`,true)}</div><div class="${showIf(k>=1)}"><p class="medium center">Our simulation: p = 0.20 and n = 100</p><div class="formula">${math(tex`\sqrt{\frac{0.20\times0.80}{100}}=0.04`,true)}</div></div><p class="big teal center ${showIf(k>=2)}" style="margin-top:30px">4 percentage points</p><p class="bottomline" style="font-size:25px">The curve has centre 20% and standard deviation 4 percentage points.</p>`},
 {title:'Probabilities under the normal curve',minutes:3,steps:8,printSteps:[0,2,3,4,5,6,7],className:'probability-slide',approximation:true,render:k=>`${k<3?approximationScene([25,100,400][k]):probabilityPicture(k)}<p class="bottomline" data-area-caption>${['25 people per sample: a visibly discrete distribution.','Larger samples give a finer range of possible estimates.','The distribution concentrates around p; the normal approximation improves.','Back to n = 100. An area under the normal curve represents a probability.','For a normal curve, mean = median: half the area lies on each side.','As in a boxplot, the interquartile range contains the central 50%.','Mean ± 1 standard deviation contains about 68% of a normal distribution.','Mean ± 2 standard deviations contains about 95% (more precisely, 95.45%).'][k]}</p>`},
 {title:'Standardising the normal approximation',minutes:2.5,steps:3,printSteps:[0,1,2],className:'transform-slide',transform:true,transformPhases:[0,1,2],render:k=>`<div data-transform-host>${standardPlot(k)}</div><div class="transform-equation">${math([tex`\widehat p\qquad\text{centre }20\%,\quad\mathrm{SE}=4\text{ points}`,tex`\widehat p-20\%\qquad\text{centre }0,\quad\mathrm{SE}=4\text{ points}`,tex`\frac{\widehat p-0.20}{0.04}\ \overset{\text{approx.}}{\sim}\ \mathcal N(0,1)`][k],true)}</div><p class="bottomline">${['Grey shadow: the standard normal, with centre 0 and standard deviation 1.','Subtract 20%: the example curve shifts to the left.','Divide by 0.04: the example expands to standard deviation 1.'][k]}</p>`},
 {title:'A quantile of the standard normal',minutes:1.5,steps:3,printSteps:[0,1,2],className:'quantile-slide',render:k=>`<p class="medium" style="margin-bottom:0">${math(tex`Z\sim\mathcal N(0,1)`)} &nbsp; ${k===2?'Bars: the same 1,000 standardised estimates':'The standard normal reference'}</p>${quantilePicture(.975,Z95,k===2)}<div class="quantile-equation">${math([tex`\Pr(Z\le z_q)=q,\qquad 0<q<1`,tex`q=0.975:\quad\Pr(Z\le z_{0.975})=0.975,\quad z_{0.975}\approx1.96`,tex`\Pr\!\left(\frac{\widehat p-p}{\mathrm{SE}(\widehat p)}\le z_q\right)\approx q`][k],true)}</div><p class="bottomline">${['The quantile z_q is the cutoff with a fraction q of the area to its left.','Example: 97.5% to the left of the upper cutoff.','The histogram is close to the normal curve. The probability is approximate.'][k]}</p>`},
 {title:'95% confidence and the remaining 5%',minutes:1.5,steps:3,printSteps:[0,1,2],className:'tails-slide',tails:true,render:k=>`<div data-tails-plot>${tailsPicture()}</div><div class="alpha-caption">${k===0?math(tex`1-\alpha=0.95\qquad\alpha=0.05`):k===1?math(tex`\alpha/2=0.025\qquad q=1-\alpha/2=0.975`):math(tex`\Pr\!\left(-z_{1-\alpha/2}\le Z\le z_{1-\alpha/2}\right)=1-\alpha`)}</div><p class="bottomline">${k===0?'Convention: α is the total area outside the chosen central region.':k===1?'Split 5% equally. The upper cutoff has 97.5% of the area to its left.':'For 95%: the two standard normal cutoffs are approximately −1.96 and +1.96.'}</p><div class="optional-controls ${showIf(k>=2)}"><button data-tail-mode="two">Central 95%</button><button data-tail-mode="lower">Optional: lower bound</button><button data-tail-mode="upper">Optional: upper bound</button></div>`},
 {title:'Returning to the prevalence scale',minutes:2,steps:3,printSteps:[0,2],className:'transform-slide',transform:true,inverse:true,render:k=>`<div data-transform-host>${standardPlot(2-k,true)}</div><div class="transform-equation">${math([tex`\Pr(-z_{0.975}\le Z\le z_{0.975})=0.95`,tex`-1.96\times\mathrm{SE}\ \le\ \widehat p-p\ \le\ 1.96\times\mathrm{SE}`,tex`p-1.96\times\mathrm{SE}\ \le\ \widehat p\ \le\ p+1.96\times\mathrm{SE}`][k],true)}</div><p class="bottomline">${['Start with the central 95% region of the standard normal.','Multiply by the standard error: the margin is about 7.8 points.','Add p: approximately 95% of estimates lie between 12.2% and 27.8%.'][k]}</p>`},
 {title:'In practice, p is unknown',minutes:1.5,steps:3,className:'unknown-slide',render:k=>`<div class="cols" style="margin-top:8px"><div><p class="medium rose">The simulation</p><p class="big">p = 20%</p><p class="medium">True standard error:<br>4 percentage points</p></div><div><p class="medium teal">The observed sample</p><p class="big">${math(tex`\widehat p=18/100=18\%`)}</p><p class="medium">${math(tex`\widehat p`)} estimates the unknown p.</p></div></div><div class="rule"></div><div class="${showIf(k>=1)}"><p class="medium">${math(tex`\widehat{\mathrm{SE}}`)} estimates the unknown ${math(tex`\mathrm{SE}(\widehat p)`)}.</p><div class="formula">${math(tex`\widehat{\mathrm{SE}}=\sqrt{\frac{\widehat p(1-\widehat p)}{n}}`,true)}</div></div><div class="${showIf(k>=2)}"><div class="formula">${math(tex`\sqrt{\frac{0.18\times0.82}{100}}\approx0.0384`,true)}</div><p class="medium center">3.84 points estimates 4 points, just as 18% estimates 20%.</p></div>`},
 {title:'An interval around the observed estimate',minutes:2.5,steps:3,printSteps:[0,1,2],className:'interval-slide',render:k=>`<p class="lead">The same distance, read from the estimate.</p><div class="formula">${math(k===0?tex`-1.96\widehat{\mathrm{SE}}\le\widehat p-p\le1.96\widehat{\mathrm{SE}}`:tex`\widehat p-1.96\widehat{\mathrm{SE}}\le p\le\widehat p+1.96\widehat{\mathrm{SE}}`,true)}</div><p class="medium center">${k===0?'About 95% of repeated samples satisfy this inequality.':math(tex`\widehat p\pm1.96\widehat{\mathrm{SE}}=18\%\pm7.53\text{ points}`)}</p><div class="${showIf(k>=1)}">${intervalLine(ci(.18))}</div><div class="general-ci ${showIf(k>=2)}">${math(tex`\text{Other confidence levels:}\quad\widehat p\pm z_{1-\alpha/2}\widehat{\mathrm{SE}}`)}</div><p class="bottomline" style="font-size:25px">${k===0?'Rearrange the inequality to put the unknown p in the middle.':k===1?'Approximate 95% confidence interval: 10.5% to 25.5%.':'What does “95% confidence” tell us about the true prevalence?'}</p>`},
 {title:'Confidence intervals in repeated samples',minutes:6,steps:11,printSteps:[1,2,4,5,6,7,8,9,10],className:'linked-coverage-slide',linkedCoverage:true,render:k=>linkedCoverageScene(coverageBuilds[k])},
 {title:'The same principle for a mean',minutes:2,steps:3,printSteps:[0,2],className:'mean-slide',render:k=>`<p class="lead">Suppose we measure systolic blood pressure in 100 adults.</p><div class="cols" style="margin:30px 0"><div><p class="medium">Suppose the sample mean is</p><div class="formula">${math(tex`\overline x=125\text{ mmHg}`,true)}</div></div><div><p class="medium">and the sample standard deviation is</p><div class="formula">${math(tex`\widehat\sigma=15\text{ mmHg}`,true)}</div></div></div><div class="rule"></div><div class="${showIf(k>=1)}"><p class="medium">Estimated standard error of the mean</p><div class="formula">${math(tex`\widehat{\mathrm{SE}}=\frac{\widehat\sigma}{\sqrt n}=\frac{15}{\sqrt{100}}=1.5\text{ mmHg}`,true)}</div></div><div class="mean-result ${showIf(k>=2)}"><p class="medium">Approximate 95% confidence interval</p><div class="formula">${math(tex`125\pm1.96\times1.5\quad:\quad[122.1,\ 127.9]\text{ mmHg}`,true)}</div></div><p class="bottomline">Individual variation: 15 mmHg. Uncertainty of the mean: 1.5 mmHg.</p>`},
 {title:'Confidence intervals for a difference',minutes:2,steps:2,printSteps:[0,1],render:k=>`<p class="medium" style="margin-bottom:10px">JAMA: complete recovery, dexamethasone versus placebo.<br>Adjusted differences in recovery, with 95% confidence intervals.</p>${jamaDifference()}<p class="bottomline" style="font-size:26px">${k?'The 24-hour interval includes 0. The 48-hour interval excludes 0.':'As before: the point is the estimate, the band is its confidence interval.'}</p>`},
 {title:'What can one confidence interval tell us?',minutes:1,steps:2,render:k=>`<p class="lead">Each band in the previous figure is one observed interval.</p><div class="reading-lines"><p>It contains the true effect or it does not.<br>With the true effect unknown, we cannot tell which.</p><p>Its width describes the precision of the estimate.</p><p>For a well-calibrated 95% procedure, about 95% of intervals<br>across repeated samples contain the true value.</p></div><p class="bottomline ${showIf(k)}">Next: how compatible are the data with a specified value, such as 0?<br>Hypothesis tests formalise this question.</p>`}
);
window.DECK={slides,draws,binomial,density,dots,P,SE,Z95,ci,intervals,coverage,histogram,bell,coverageBuilds,ensemble,coverageSummary,exactCoverage,standardGeometry,confidenceLevels,sampleIllustration};
