 
slides[0].title='Statistical inference: proportions and means';
;
slides[3].render=k=>`<p class="lead">What proportion of adults in a defined region have the disease?</p><div class="cols" style="margin-top:50px"><div><p class="medium">For this simulation, we choose</p><p class="big rose">p = 20%</p><p class="medium">Knowing the answer lets us study<br>how estimates vary.</p></div><div class="${showIf(k)}"><p class="medium">Our sampling model</p><p class="medium">Independent observations.<br>The same disease probability p<br>for every observation.</p><p class="small muted">Disease status is recorded accurately.</p></div></div><p class="bottomline">In a real study, the population prevalence is unknown.</p>`;
;
coverageBuilds.splice(0,coverageBuilds.length,
 {n:100,level:95,total:1,phase:2},{n:100,level:95,total:3,phase:2},{n:100,level:95,total:4,phase:2},
 {n:100,level:95,total:1000,phase:0},{n:100,level:95,total:1000,phase:1},{n:100,level:95,total:1000,phase:2},
 {n:400,level:95,total:1000,phase:2});
slides.splice(7,slides.length-7,
 {title:'The distribution of sample proportions',minutes:3,steps:4,printSteps:[0,1,2,3],className:'counted-slide',storyHistogram:true,render:k=>histogramReading(k)},
 {title:'Sample size and the normal approximation',minutes:3,steps:4,printSteps:[2,3],className:'sizes-slide',sizeComparison:true,render:sizeComparison},
 {title:'The central limit theorem and standard error',minutes:2.5,steps:3,printSteps:[1,2],className:'theorem-slide',render:k=>`<p class="medium">${math(tex`\widehat p`)} averages n independent 0/1 observations with the same probability p.</p><p class="medium">For large n <span class="muted">(people in each sample)</span></p><div class="formula center">${math(tex`\widehat p\ \overset{\text{approx.}}{\sim}\ \mathcal N\!\left(p,\,\frac{p(1-p)}{n}\right)`,true)}</div><div class="parameter-line"><span>${math(tex`\text{Mean}=p`)}</span><span>${math(tex`\text{Variance}=p(1-p)/n`)}</span></div>${k<2?`<div class="${showIf(k>=1)}"><div class="formula center">${math(tex`\mathrm{SE}(\widehat p)=\sqrt{\frac{p(1-p)}n}=\frac{\sqrt{p(1-p)}}{\sqrt n}`,true)}</div><p class="medium center">At p = 0.20 and n = 100: SE = 0.04, or 4 percent points.</p></div>`:`<div class="density-definition"><p class="small center">The density of the approximating normal curve</p><div class="formula">${math(tex`f_n(x)=\frac{1}{\sqrt{2\pi\sigma_n^2}}\exp\!\left(-\frac{(x-p)^2}{2\sigma_n^2}\right),\qquad\sigma_n^2=\frac{p(1-p)}n`,true)}</div></div>`}<p class="bottomline">${k===2?'The curve describes the distribution of the estimator; it is not the estimator itself.':'Standard error is the standard deviation of the estimates across possible samples.'}</p>`},
 {title:'Reading areas under the normal curve',minutes:2,steps:4,printSteps:[0,1,2,3],className:'normal-reading',render:normalAreaReading},
 {title:'Standardising the normal approximation',minutes:2.5,steps:3,printSteps:[0,1,2],className:'transform-slide narrative-transform',transform:true,transformPhases:[0,1,2],render:k=>`<div data-transform-host>${standardPlot(k)}</div><div class="transform-equation">${math([tex`\widehat p\qquad\text{centre }0.20,\quad\mathrm{SE}=0.04`,tex`\widehat p-0.20\qquad\text{centre }0,\quad\mathrm{SE}=0.04`,tex`\frac{\widehat p-0.20}{0.04}\ \overset{\text{approx.}}{\sim}\ \mathcal N(0,1)`][k],true)}</div><p class="bottomline">${['Follow 16%, 20%, 24%: one standard error below, at, and above the centre.','Subtract the centre: those positions become −0.04, 0, +0.04.','Divide by the standard error: the same positions become −1, 0, +1.'][k]}</p>`},
 {title:'Normal quantiles and a central 95%',minutes:3,steps:4,printSteps:[0,1,2,3],className:'quantile-slide merged-quantiles',render:k=>`<p class="medium">${math(tex`Z\sim\mathcal N(0,1)`)} &nbsp; The standard normal reference</p>${k===0?quantilePicture(.975,Z95):tailsPicture()}<div class="quantile-equation">${math([tex`\Pr(Z\le z_q)=q,\quad0<q<1;\qquad z_{0.975}\approx1.96`,tex`1-\alpha=0.95\quad\Rightarrow\quad\alpha=0.05`,tex`\alpha/2=0.025,\qquad q=1-\alpha/2=0.975`,tex`\Pr\!\left(\frac{\widehat p-p}{\mathrm{SE}(\widehat p)}\in[-z_{1-\alpha/2},z_{1-\alpha/2}]\right)\approx1-\alpha`][k],true)}</div><p class="bottomline">${['A quantile is a cutoff. Here, 97.5% of the normal area lies to its left.','95% in the centre leaves 5% outside: this remainder is called α.','Two equal tails: 2.5% each. The upper cutoff is the 97.5% quantile.','For standardised estimates, this normal probability is approximate.'][k]}</p>`},
 {title:'Returning to the prevalence scale',minutes:2,steps:3,printSteps:[0,2],className:'transform-slide narrative-transform',transform:true,inverse:true,transformPhases:[2,1,0],render:k=>`<div data-transform-host>${standardPlot(2-k,true)}</div><div class="transform-equation">${math([tex`\Pr(-z_{0.975}\le Z\le z_{0.975})=0.95`,tex`-1.96\,\mathrm{SE}\le\widehat p-p\le1.96\,\mathrm{SE}`,tex`p-1.96\,\mathrm{SE}\le\widehat p\le p+1.96\,\mathrm{SE}`][k],true)}</div><p class="bottomline">${['Start with 95% in the standard normal reference.','Multiply by 0.04: the distance is about 7.84 percent points.','Add 20%: approximately 95% of estimates fall between 12.2% and 27.8%.'][k]}</p>`},
 {title:'In practice, p is unknown',minutes:1.5,steps:2,printSteps:[0,1],className:'unknown-slide',render:k=>`<p class="lead">We have one sample: 18 cases among 100 people.</p><div class="cols" style="margin:35px 0"><div><p class="medium">Estimate the prevalence</p><div class="formula">${math(tex`\widehat p=18/100=0.18`,true)}</div></div><div><p class="medium">Estimate its standard error</p><div class="formula">${math(tex`\widehat{\mathrm{SE}}=\sqrt{\frac{\widehat p(1-\widehat p)}n}`,true)}</div></div></div><div class="rule"></div><div class="${showIf(k)}"><div class="formula center">${math(tex`\widehat{\mathrm{SE}}=\sqrt{\frac{0.18\times0.82}{100}}\approx0.0384`,true)}</div><p class="medium center">3.84 percent points</p></div><p class="bottomline">${k?'In our simulation, this estimates 4 percent points, just as 18% estimates 20%.':'The unknown population value is replaced by an estimate from the sample.'}</p>`},
 {title:'An interval around the observed estimate',minutes:2.5,steps:3,printSteps:[0,1,2],className:'interval-slide',render:k=>`<p class="lead">Read the same distance from the observed estimate.</p><div class="formula">${math(k===0?tex`|\widehat p-p|\le1.96\,\widehat{\mathrm{SE}}`:tex`\widehat p-1.96\,\widehat{\mathrm{SE}}\le p\le\widehat p+1.96\,\widehat{\mathrm{SE}}`,true)}</div><p class="medium center">${k===0?'An event with approximately 95% probability under the sampling model.':math(tex`\widehat p\pm E=18\%\pm7.53\text{ percent points}`)}</p><div class="${showIf(k>=1)}">${intervalLine(ci(.18))}</div><div class="general-ci ${showIf(k>=2)}">${math(tex`E=z_{1-\alpha/2}\,\widehat{\mathrm{SE}}\qquad\text{Margin of error}`)}</div><p class="bottomline">${k===0?'Rearrange to put the unknown p between the two sample-based bounds.':k===1?'Approximate 95% confidence interval: 10.5% to 25.5%.':'The margin of error is the half-width of this symmetric interval.'}</p>`},
 {title:'Confidence intervals in repeated samples',minutes:4,steps:7,printSteps:[1,2,3,4,5,6],className:'linked-coverage-slide',linkedCoverage:true,render:k=>linkedCoverageScene(coverageBuilds[k])},
 {title:'Confidence intervals for a population mean',minutes:2,steps:3,printSteps:[0,1,2],className:'mean-slide restored-mean',render:k=>`<p class="lead">Suppose we measure systolic blood pressure in 100 adults.</p><p class="medium muted">Target: the population mean ${math(tex`\mu`)}.</p><div class="cols mean-summaries"><div><p class="medium">Suppose the sample mean is</p><div class="formula">${math(tex`\overline x=125\text{ mmHg}`,true)}</div></div><div><p class="medium">and the sample standard deviation is</p><div class="formula">${math(tex`\widehat\sigma=15\text{ mmHg}`,true)}</div></div></div><div class="rule"></div><div class="${showIf(k>=1)}"><p class="medium">Estimated standard error of the mean</p><div class="formula">${math(tex`\widehat{\mathrm{SE}}=\frac{\widehat\sigma}{\sqrt n}=\frac{15}{\sqrt{100}}=1.5\text{ mmHg}`,true)}</div></div><div class="mean-result ${showIf(k>=2)}"><p class="medium">Approximate 95% confidence interval: ${math(tex`\overline x\pm E`)}</p><div class="formula">${math(tex`125\pm1.96\times1.5\quad:\quad[122.1,\ 127.9]\text{ mmHg}`,true)}</div></div><p class="bottomline">${['Individual variation is 15 mmHg. How precisely have we estimated the mean?','Individual variation: 15 mmHg. Uncertainty of the mean: 1.5 mmHg.','Margin E = 2.94 mmHg. The same construction applies to a mean.'][k]}</p>`},
 {title:'Planning a sample size',minutes:2,steps:3,printSteps:[1,2],className:'planning-slide',render:k=>`<p class="medium">For prevalence, choose a confidence level, a target margin E<br>and a planning value for p.</p><div class="formula center">${math(tex`n\ge\frac{z_{1-\alpha/2}^{\,2}\,p_{\rm plan}(1-p_{\rm plan})}{E^2}`,true)}</div><div class="${showIf(k>=1)}"><p class="medium center">95% confidence, planning prevalence 20%</p><div class="formula center">${math(k===2?tex`E=0.02:\quad\frac{1.96^2\times0.20\times0.80}{0.02^2}=1536.64\quad\Rightarrow\quad n=1537`:tex`E=0.04:\quad\frac{1.96^2\times0.20\times0.80}{0.04^2}=384.16\quad\Rightarrow\quad n=385`,true)}</div><p class="medium center teal">${k===2?'Target margin: ±2 percent points':'Target margin: ±4 percent points'}</p></div><p class="bottomline">${k===2?'Half the target margin requires about four times n. This plans precision, not power.':'Round up. This plans precision under the sampling model; it is not a power calculation.'}</p>`},
 {title:'Reading the JAMA confidence intervals',minutes:1,steps:1,render:k=>`<p class="medium">Dexamethasone versus placebo: adjusted differences in recovery.</p>${jamaDifference()}<p class="jama-source">Source: Hayward et al., <em>JAMA</em> 2017;317:1535–1543, Figure 2 (redrawn).</p><p class="bottomline">The point estimates the difference. The interval describes its precision.<br>For a difference, 0 means no effect.</p>`},
 {title:'One sample, estimation and a new question',minutes:1.5,steps:2,printSteps:[0,1],className:'closing-slide',render:k=>`<p class="lead">One sample already gives an estimate and information about its precision.</p><div class="reading-lines"><p>A 95% confidence procedure covers the true value in about 95% of repetitions, when its approximation is adequate.</p><p>We cannot tell whether this particular interval contains the unknown true value.</p></div><div class="closing-question ${showIf(k)}"><p class="medium rose">Suppose a population value were true.</p><p class="medium">Would the data we observed be surprising?<br>Hypothesis tests formalise that question.</p></div><p class="bottomline">${k?'Same sample, a different question. Tests also control a procedure’s error rate.':'We do not need to collect repeated samples to use the interval.'}</p>`}
);

for(const slide of slides){const render=slide.render;slide.render=(...args)=>render(...args).replaceAll('percentage points','percent points');}
Object.assign(window.DECK,{slides,coverageBuilds,narrativeGeometry,empiricalWindow,planningNumbers});
