const deckMeta={title:'Hypothesis testing',course:3,version:2,date:'21 September 2026',pdf:'M2_topic9_hypothesis-testing_26-27.pdf',description:'A visual decision rule on the prevalence scale, matching confidence intervals and p-values, then the published JAMA conclusions.'};



const scores=[18,25,30].map(k=>sampleStats(k));
const slides=[
{title:'Hypothesis testing',steps:1,printSteps:[0],minutes:.5,className:'title-slide',render:()=>`<p class="course">DAS · Statistics</p><h1>Hypothesis testing</h1><p class="title-question">A decision about a population, based on a sample</p><div class="route"><span>Hypotheses and decisions</span><span>Confidence intervals and p-values</span><span>Interpreting a study</span></div>`},
{title:'Does the drug have an effect?',steps:3,printSteps:[0,2],minutes:2,className:'narrative',render:k=>`<p class="lead">The JAMA trial compared dexamethasone with placebo.</p><div class="medical-comparison"><div><p class="treatment">Dexamethasone</p><p>Proportion of patients whose sore throat has resolved</p></div><div><p class="treatment">Placebo</p><p>Proportion of patients whose sore throat has resolved</p></div></div>${reveal(k>=1,`<p class="callout">${math(tex`H_0`)}: no difference between the treatments.<br>${math(tex`H_1`)}: a difference between the treatments.</p>`)}<p class="bottomline">${k>=2?'We compare population outcomes using two randomly assigned groups.':'The outcome and the time of measurement define what “an effect” means.'}</p>`},
{title:'An estimate, an interval, a decision',steps:3,printSteps:[0,2],minutes:2,className:'narrative',render:k=>`<p class="lead">A simpler example: 18 cases among 100 adults.</p>${ciChart([{name:'Our sample',est:.18,lo:.1047006426365767,hi:.2552993573634233}])}<p class="bottomline">${['Estimated prevalence: 18%. An approximate 95% interval: [10.5%, 25.5%].','Could the true population prevalence be 20%?','How can we turn this comparison into a decision rule?'][k]}</p>`},
{title:'Hypotheses and significance level',steps:4,printSteps:[3],minutes:3,className:'narrative',render:k=>`<p class="lead">Our question concerns the population prevalence ${math('p')}.</p><div class="hypothesis-blocks"><div><p class="medium">Null hypothesis</p>${formula(tex`H_0:p=0.20`)}</div>${reveal(k>=1,`<p class="medium">Alternative hypothesis</p>${formula(tex`H_1:p\ne0.20`)}`)}${reveal(k>=2,'<p class="medium">These hypotheses exclude each other.</p>')}${reveal(k>=3,`<p class="callout">Choose the significance level in advance: ${math(tex`\alpha=0.05`)}.</p>`)}</div><p class="bottomline small">The significance level sets how extreme a result must be to reject H₀.</p>`},
{title:'Is our observation unusually far from 20%?',steps:5,printSteps:[0,2,4],minutes:4.5,className:'narrative curve-slide',render:k=>`<p class="lead">Suppose H₀ is true. Take samples of 100 adults.</p>${proportionFigure({markers:k===0?[]:k===1||k===2?[18]:k===3?[18,25]:[18,25,30],regions:k>=2})}<p class="readout">${['Sample proportions vary around the true prevalence of 20%.','18% is close to 20%. But how close is close enough?','At a 5% significance level, the two extreme regions contain 2.5% each.','25% is also inside the central region.','30% falls in an extreme region under H₀.'][k]}</p><p class="bottomline small">Normal approximation to the sampling distribution under H₀.</p>`},
{title:'One sample, one decision',steps:4,printSteps:[0,2,3],minutes:3,className:'narrative curve-slide',render:k=>`<p class="lead">Same hypothesis and significance level: ${math(tex`H_0:p=0.20,\quad\alpha=0.05`)}.</p>${proportionFigure({markers:k===3?[18,25,30]:[[18],[25],[30]][k],regions:true})}<p class="readout">${['18%: inside the central region. We do not reject H₀.','25%: inside the central region. We do not reject H₀.','30%: outside the central region. We reject H₀ at 5%.','Inside: do not reject H₀. Outside: reject H₀ at the chosen level.'][k]}</p><p class="bottomline">Not rejecting H₀ does not establish that the true prevalence is 20%.</p>`},
{title:'The significance level changes the rule',steps:3,printSteps:[0,1,2],minutes:4,className:'narrative curve-slide',render:k=>{const a=[.05,.30,.01][k];return `<p class="lead">Same observations. Significance level: ${math(tex`\alpha=${a.toFixed(2)}`)}.</p>${proportionFigure({alpha:a,markers:[18,25,30],regions:true})}<p class="readout">${['At 5%, only 30% leads to rejection.','At 30%, both 25% and 30% lead to rejection.','At 1%, none of these three observations leads to rejection.'][k]}</p><p class="bottomline small">Compare rules chosen in advance. The 30% level is deliberately permissive for illustration.</p>`;}},
{title:'Confidence intervals give the matching decision',steps:3,printSteps:[0,1,2],minutes:3.5,className:'narrative curve-slide',render:k=>{const a=[.05,.30,.01][k];return `<p class="lead">Two-sided test at ${pct(a)}. Corresponding confidence level: ${pct(1-a)}.</p>${matchingIntervals(a)}<p class="readout">An interval that excludes 20% gives a rejection of H₀.</p><p class="bottomline small">These intervals match the test shown here. Greater confidence gives wider intervals.</p>`;}},
{title:'The p-value measures how extreme the result is',steps:4,printSteps:[1,3],minutes:4,className:'narrative curve-slide',render:k=>{const cases=k<2?18:k===2?25:30,d=sampleStats(cases);return `<p class="lead">If H₀ were true, how often would a result be at least this far from 20%?</p>${proportionFigure({markers:[cases],regions:true,pvalue:k>=1})}<p class="readout">${k===0?'The pink limits still show the decision rule at 5%.':`Shaded area: p-value ≈ ${d.pvalue.toFixed(3)}. ${d.reject?'Reject':'Do not reject'} H₀ at 5%.`}</p><p class="bottomline small">${k>=1?'The p-value follows the observation. The significance level stays fixed.':'For a two-sided question, include equally extreme results on both sides.'}</p>`;}},
{title:'The z-score is a way to calculate that area',steps:3,printSteps:[2],minutes:2,className:'narrative',render:k=>`<p class="lead">Express the observed distance in standard errors.</p><div style="margin-top:40px">${formula(tex`z_{\mathrm{obs}}=\frac{\text{estimate}-\text{value in }H_0}{\text{standard error under }H_0}`)}</div>${reveal(k>=1,'<div class="score-parts"><p>18 cases: z = −0.50</p><p>30 cases: z = 2.50</p></div>')}${reveal(k>=2,formula(tex`\text{two-sided p-value}\approx2\Pr(Z\ge|z_{\mathrm{obs}}|)`))}<p class="bottomline">Software calculates the area. The graph explains its meaning.</p>`},
{title:'One-sided and two-sided questions',steps:3,printSteps:[0,1,2],minutes:4,className:'narrative curve-slide',render:k=>{const modes=['two','right','left'],qs=['Different from 20%?','Higher than 20%?','Lower than 20%?'],hs=[tex`H_0:p=0.20,\quad H_1:p\ne0.20`,tex`H_0:p\le0.20,\quad H_1:p>0.20`,tex`H_0:p\ge0.20,\quad H_1:p<0.20`];return `<p class="lead">${qs[k]} ${math(hs[k])}</p>${proportionFigure({markers:[30],regions:true,pvalue:true,mode:modes[k]})}<p class="readout">${math([tex`\text{p-value}\approx2\Pr(Z\ge|z_{\mathrm{obs}}|)`,tex`\text{p-value}\approx\Pr(Z\ge z_{\mathrm{obs}})`,tex`\text{p-value}\approx\Pr(Z\le z_{\mathrm{obs}})`][k])}</p><p class="bottomline small">Choose the direction before seeing the result. The same sample answers different questions.</p>`;}},
{title:'The same result, different questions',steps:2,printSteps:[1],minutes:1.5,className:'narrative',render:k=>`<p class="lead">30 cases among 100 adults.</p><table class="table"><thead><tr><th>Question</th><th>p-value</th><th>Decision at 5%</th></tr></thead><tbody><tr><td>Different from 20%?</td><td>0.0124</td><td>Reject H₀</td></tr><tr><td>Higher than 20%?</td><td>0.0062</td><td>Reject H₀</td></tr><tr><td>Lower than 20%?</td><td>0.9938</td><td>Do not reject H₀</td></tr></tbody></table>${reveal(k>=1,'<p class="bottomline">A hoped-for benefit does not automatically make a test one-sided.</p>')}`},
{title:'When the Normal calculation is appropriate',steps:3,printSteps:[2],minutes:2,className:'narrative',render:k=>`<div class="stack"><p class="medium">The sample must support the population question.</p>${reveal(k>=1,'<p class="medium">This simple calculation assumes independent observations.</p>')}${reveal(k>=2,'<p class="medium">The sample needs enough cases and non-cases for a useful Normal approximation.</p>')}</div><p class="bottomline">Small samples, rare events or dependent data may require another method.</p>`},
{title:'Back to the JAMA confidence intervals',steps:3,printSteps:[0,2],minutes:2.5,className:'narrative compact',render:k=>`<p class="lead">Published differences in symptom resolution: dexamethasone minus placebo.</p>${jamaPlot()}<p class="jama-source">Source: Hayward et al., <em>JAMA</em> 2017;317:1535–1543, Figure 2 (redrawn).</p><p class="bottomline">${['No treatment difference corresponds to 0.','At 24 h, the interval contains 0.','At 48 h, the interval excludes 0 and lies on the side favouring dexamethasone.'][k]}</p>`},
{title:'The published p-values and the conclusion',steps:4,printSteps:[1,3],minutes:6.5,className:'narrative compact',render:k=>k<2?`<p class="lead">H₀: no difference in symptom resolution between treatments.</p>${jamaPlot(1)}<p class="jama-source">Source: Hayward et al., <em>JAMA</em> 2017;317:1535–1543.</p><p class="bottomline">${k===0?'24 h: p-value = 0.14. We do not reject H₀.':'48 h: p-value = 0.03. We reject H₀ at the reported 5% level.'}</p>`:`<div class="stack"><p class="medium"><strong>24 h, primary outcome</strong><br>The study did not demonstrate a statistically significant difference.</p><p class="medium"><strong>48 h, secondary outcome</strong><br>The study found a difference favouring dexamethasone in an exploratory analysis.</p>${reveal(k>=3,'<p class="medium">Non-significant does not establish no effect.<br>Statistically significant does not establish clinical importance.</p>')}</div><p class="jama-source">Source: Hayward et al., <em>JAMA</em> 2017;317:1535–1543.</p><p class="bottomline small">The article reports two-sided tests, without adjustment for multiple comparisons.</p>`}
];

 
deckMeta.version=3;
slides.find(s=>s.title==='An estimate, an interval, a decision').title='Back to our simple prevalence example';

 
deckMeta.version=4;

const questionComparisonSlide=slides.find(s=>s.title==='The same result, different questions');
questionComparisonSlide.steps=1;
questionComparisonSlide.printSteps=[0];
questionComparisonSlide.render=()=>`<p class="lead">30 cases among 100 adults.</p><table class="table"><thead><tr><th>Question</th><th>p-value</th><th>Decision at 5%</th></tr></thead><tbody><tr><td>Different from 20%?</td><td>0.0124</td><td>Reject H₀</td></tr><tr><td>Higher than 20%?</td><td>0.0062</td><td>Reject H₀</td></tr><tr><td>Lower than 20%?</td><td>0.9938</td><td>Do not reject H₀</td></tr></tbody></table>`;
;

const publishedConclusionSlide=slides.find(s=>s.title==='The published p-values and the conclusion');
const previousConclusionRender=publishedConclusionSlide.render;
publishedConclusionSlide.render=k=>previousConclusionRender(k)
  .replace('<strong>24 h, primary outcome</strong>','24 h, primary outcome')
  .replace('<strong>48 h, secondary outcome</strong>','48 h, secondary outcome');

slides.push({title:'Thank you',steps:1,printSteps:[0],minutes:0,className:'thank-you-slide',render:()=>'<p class="thank-you-message">Thank you very much for your attention</p>'});
