const stage=document.getElementById('stage'),isPrint=new URLSearchParams(location.search).has('print');let current=0,step=0,sceneTimer=null,sceneConfig=null;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function markup(i,k,print=false){const s=slides[i];return `<section class="slide ${s.className||''}" data-slide="${i+1}" data-step="${k}" aria-label="Slide ${i+1}: ${s.title}"><header><h1>${s.title}</h1></header><div class="content">${s.render(k,print)}</div>${print?`<span class="print-state">${i+1}${s.printSteps?.length>1?' / step '+(k+1):''}</span>`:''}</section>`;}
function scale(){if(isPrint)return;const s=Math.min(innerWidth/1280,(innerHeight-65)/720);stage.style.transform=`scale(${s})`;stage.style.left=`${(innerWidth-1280*s)/2}px`;stage.style.top=`${Math.max(0,(innerHeight-65-720*s)/2)}px`;}
function stop(){clearTimeout(sceneTimer);sceneTimer=null;}
function notes(){const panel=document.getElementById('notes');if(!panel)return;const s=slides[current];panel.innerHTML=`<button data-close-notes>Close</button><h2>${current+1}. ${s.title}</h2>${s.spoken?`<p><strong>Suggested narration</strong><br>${s.spoken}</p>`:""}<p>${s.notes}</p><p class="source">Source: ${s.source}</p>`;document.querySelector('[data-close-notes]').onclick=()=>toggle('notes');}
function bindScene(){const host=stage.querySelector('[data-interval-scene]');if(!host)return;sceneConfig=JSON.parse(host.dataset.config);const update=()=>{host.innerHTML=intervalScene({...sceneConfig,controls:true});stage.dataset.studyCount=sceneConfig.total;bindSceneButtons();};const bindSceneButtons=()=>{host.querySelector('[data-window]').onclick=()=>{stop();sceneConfig.start=(sceneConfig.start+40)%Math.max(40,sceneConfig.total);update();};host.querySelector('[data-all]').onclick=()=>{stop();sceneConfig.total=1000;sceneConfig.start=0;update();};host.querySelector('[data-repeat]').onclick=()=>{if(sceneTimer){stop();host.querySelector('[data-repeat]').textContent='Continue studies';return;}if(sceneConfig.total>=1000)sceneConfig.total=0;const tick=()=>{sceneConfig.total=Math.min(1000,sceneConfig.total+(reduced()?1000:sceneConfig.total<5?1:sceneConfig.total<40?5:40));sceneConfig.start=Math.max(0,sceneConfig.total-40);update();if(sceneConfig.total<1000){host.querySelector('[data-repeat]').textContent='Pause';sceneTimer=setTimeout(tick,sceneConfig.total<5?600:160);}else stop();};tick();};};bindSceneButtons();}
function showSlide(i,k=0,animate=true){stop();const oldShapes=shapeSnapshot(stage);const old={};stage.querySelectorAll('[data-key]').forEach(e=>old[e.dataset.key]=getComputedStyle(e).transform);current=Math.max(0,Math.min(slides.length-1,i));step=Math.max(0,Math.min(slides[current].steps-1,k));stage.innerHTML=markup(current,step);if(animate)morphShapes(stage,oldShapes);if(animate&&!reduced()){stage.querySelectorAll('[data-key]').forEach(e=>{const from=old[e.dataset.key];if(from&&from!=='none'&&from!==e.style.transform)e.animate([{transform:from},{transform:e.style.transform}],{duration:950,easing:'ease-in-out'});});stage.querySelectorAll('[data-appear],.revealed').forEach(e=>e.animate([{opacity:0},{opacity:1}],{duration:600}));stage.querySelectorAll('[data-grow]').forEach(e=>{e.style.transformOrigin='315px center';e.animate([{transform:'scaleX(0)'},{transform:'scaleX(1)'}],{duration:950,easing:'ease-out'});});}document.getElementById('position').textContent=`${current+1} / ${slides.length} · ${step+1} / ${slides[current].steps}`;document.getElementById('prev').disabled=current===0&&step===0;document.getElementById('next').disabled=current===slides.length-1&&step===slides[current].steps-1;history.replaceState(null,'',`#${current+1}.${step+1}`);notes();bindScene();bindPowerControls();scale();}
function next(){if(step<slides[current].steps-1)showSlide(current,step+1);else if(current<slides.length-1)showSlide(current+1);}
function previous(){if(step>0)showSlide(current,step-1);else if(current>0)showSlide(current-1,slides[current-1].steps-1);}
function toggle(id){const e=document.getElementById(id),button=document.getElementById(id==='notes'?'notesButton':'overviewButton');if(!e||!button)return;e.hidden=!e.hidden;button.setAttribute('aria-expanded',String(!e.hidden));}
window.showSlide=showSlide;window.DECK={slides,meta:deckMeta};
if(isPrint){document.body.classList.add('print-mode');stage.innerHTML=slides.flatMap((s,i)=>(s.printSteps||[s.steps-1]).map(k=>markup(i,k,true))).join('');}
else{document.getElementById('prev').onclick=previous;document.getElementById('next').onclick=next;const notesButton=document.getElementById('notesButton');if(notesButton)notesButton.onclick=()=>toggle('notes');document.getElementById('overviewButton').onclick=()=>toggle('overview');document.getElementById('fullButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.getElementById('overview').innerHTML='<button data-close-overview>Close</button><h2>Slides</h2>'+slides.map((s,i)=>`<button data-jump="${i}">${i+1}. ${s.title}</button>`).join('');document.querySelector('[data-close-overview]').onclick=()=>toggle('overview');document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{showSlide(+b.dataset.jump);toggle('overview');});addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||(e.target.tagName==='BUTTON'&&e.key===' '))return;if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();next();}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();previous();}else if(e.key==='Home')showSlide(0);else if(e.key==='End')showSlide(slides.length-1,slides.at(-1).steps-1);else if(e.key==='Escape'){const notes=document.getElementById('notes');if(notes)notes.hidden=true;document.getElementById('overview').hidden=true;}else if(e.key==='n'&&notesButton)toggle('notes');});addEventListener('resize',scale);addEventListener('hashchange',()=>{const m=location.hash.match(/#(\d+)\.(\d+)/);if(m)showSlide(+m[1]-1,+m[2]-1,false);});const start=location.hash.match(/#(\d+)\.(\d+)/);showSlide(start?+start[1]-1:0,start?+start[2]-1:0,false);}
