
window.DECK={slides,records,observed,series,sleep,paired,stats};
const stage=document.getElementById('stage');let current=0,step=0;
const isPrint=new URLSearchParams(location.search).has('print');
function markup(i,k){const s=slides[i];return `<section class="slide ${s.className||''}" data-slide="${i+1}" data-step="${k}" aria-label="Slide ${i+1}: ${s.title}"><header><h1>${s.title}</h1></header><div class="content">${s.render(k)}</div></section>`}
window.slideMarkup=markup;
function scale(){if(isPrint)return;const s=Math.min(innerWidth/1280,(innerHeight-65)/720);stage.style.transform=`scale(${s})`;stage.style.left=`${(innerWidth-1280*s)/2}px`;stage.style.top=`${Math.max(0,(innerHeight-65-720*s)/2)}px`}
function show(i,k,animate=true){
 const old={};stage.querySelectorAll('[data-key]').forEach(el=>old[el.dataset.key]={transform:el.style.transform,opacity:el.style.opacity,tag:el.tagName,x:+el.getAttribute('x'),y:+el.getAttribute('y'),width:+el.getAttribute('width'),height:+el.getAttribute('height')});
 const oldCounts={};stage.querySelectorAll('[data-count]').forEach(el=>oldCounts[el.dataset.count]=+el.dataset.value);
 current=Math.max(0,Math.min(slides.length-1,i));step=Math.max(0,Math.min(slides[current].steps-1,k));stage.innerHTML=markup(current,step);window.renderLatexContent(stage);
 if(animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
  stage.querySelectorAll('g[data-key]').forEach(el=>{const prev=old[el.dataset.key];if(prev&&!(el.dataset.key==='value-21'&&prev.opacity==='0'&&el.style.opacity!=='0'))el.animate([{transform:prev.transform,opacity:prev.opacity||1},{transform:el.style.transform,opacity:el.style.opacity||1}],{duration:850,easing:'ease-in-out'});else if(el.dataset.key==='value-21')el.animate([{transform:'translate(1190px,148px)',opacity:0},{transform:el.style.transform,opacity:el.style.opacity}],{duration:850,easing:'ease-out'})});
  stage.querySelectorAll('rect[data-key]').forEach(el=>{const p=old[el.dataset.key],x=+el.getAttribute('x'),y=+el.getAttribute('y'),w=+el.getAttribute('width'),h=+el.getAttribute('height');if(el.dataset.key==='box'&&!p){el.style.transformOrigin=`${x}px 164px`;el.animate([{transform:'scaleX(0)'},{transform:'scaleX(1)'}],{duration:650,easing:'ease-out'})}else if(p&&w&&h){el.style.transformOrigin=`${x}px ${y+h}px`;const hidden=p.opacity==='0';el.animate([{transform:`translate(${p.x-x}px,${hidden?0:p.y+p.height-y-h}px) scale(${p.width/w},${hidden?0:p.height/h})`,opacity:p.opacity||1},{transform:'none',opacity:el.style.opacity||1}],{duration:850,easing:'ease-in-out'})}});
  stage.querySelectorAll('[data-reveal]').forEach(el=>el.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'none'}],{duration:650,easing:'ease-out'}));
  stage.querySelectorAll('[data-count]').forEach(el=>{const from=oldCounts[el.dataset.count],to=+el.dataset.value;if(from===undefined||from===to)return;const start=performance.now();function update(now){if(!el.isConnected)return;const t=Math.min(1,(now-start)/850),value=from+(to-from)*(t*t*(3-2*t));window.updateLatexLabel(el,Number.isInteger(to)&&Number.isInteger(from)?Math.round(value):value.toFixed(1));if(t<1)requestAnimationFrame(update)}requestAnimationFrame(update)});
 }
 document.getElementById('position').textContent=`${current+1} / ${slides.length}${slides[current].steps>1?` · step ${step+1}/${slides[current].steps}`:''}`;document.getElementById('prev').disabled=current===0&&step===0;document.getElementById('next').disabled=current===slides.length-1&&step===slides[current].steps-1;history.replaceState(null,'',`#${current+1}.${step}`);scale();}
window.showSlide=(i,k=0)=>show(i,k,false);
function next(){if(step<slides[current].steps-1)show(current,step+1);else if(current<slides.length-1)show(current+1,0)}
function prev(){if(step>0)show(current,step-1);else if(current>0)show(current-1,slides[current-1].steps-1)}
function toggle(id,button){const a=document.getElementById(id);a.hidden=!a.hidden;document.getElementById(button).setAttribute('aria-expanded',!a.hidden)}
if(isPrint){document.body.classList.add('print-mode');stage.innerHTML=slides.map((s,i)=>Array.from({length:s.steps},(_,k)=>markup(i,k)).join('')).join('')}
else{const [i,k]=location.hash.slice(1).split('.').map(Number);show((i||1)-1,k||0,false);document.getElementById('next').onclick=next;document.getElementById('prev').onclick=prev;document.getElementById('overviewButton').onclick=()=>toggle('overview','overviewButton');document.getElementById('fullButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.getElementById('overview').innerHTML='<h2>Slides</h2>'+slides.map((s,i)=>`<button data-goto="${i}">${i+1}. ${s.title}</button>`).join('');document.getElementById('overview').onclick=e=>{const b=e.target.closest('[data-goto]');if(b){show(+b.dataset.goto,0);toggle('overview','overviewButton')}};addEventListener('resize',scale);addEventListener('keydown',e=>{if(e.target.closest('button')&&[' ','Enter'].includes(e.key))return;if(['ArrowRight','ArrowDown',' ','PageDown'].includes(e.key)){e.preventDefault();next()}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();prev()}else if(e.key==='Home')show(0,0);else if(e.key==='End')show(slides.length-1,0);else if(e.key==='Escape'){document.getElementById('overview').hidden=true;document.getElementById('overviewButton').setAttribute('aria-expanded',false)}})}
